using CodeChops.ImplementationDiscovery.Attributes;

namespace CodeChops.ImplementationDiscovery.UnitTests.EmptyImplementations;

[DiscoverImplementations]
public abstract partial record EmptyImplementationsMock;