// using System.Text;
//
// namespace CodeChops.ImplementationDiscovery.SourceGeneration.SourceBuilders;
//
// [Generator]
// public class ProxyInitializationGenerator : IIncrementalGenerator
// {
// 	public void Initialize(IncrementalGeneratorInitializationContext initializationContext)
// 	{
// 		try
// 		{
// 			initializationContext.RegisterSourceOutput(source: initializationContext.AnalyzerConfigOptionsProvider, CreateSource);
// 		}
//
// 		catch (Exception e)
// 		{
// 			initializationContext.RegisterPostInitializationOutput(c => c.AddSource($"{nameof(ProxyInitializationGenerator)}_Exception_{Guid.NewGuid()}", SourceText.From($"/*{e}*/", Encoding.UTF8)));
// 		}
// 	}
//
// 	private static void CreateSource(SourceProductionContext context, AnalyzerConfigOptionsProvider configOptionsProvider)
// 	{
// 		configOptionsProvider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var rootNamespace);
//
// 		if (rootNamespace == "CodeChops.ImplementationDiscovery")
// 			return;
// 			
// 		var code = $@"// <auto-generated />
// using Microsoft.Extensions.DependencyInjection;
//
// namespace CodeChops.ImplementationDiscovery;
//
// public static class ProxyInitializationExtensions
// {{
// 	public static IServiceCollection InitializeProxyImplementations(this IServiceCollection services)
// 	{{
// 		// Calls the type constructor of all types that are implemented in this assembly.
// 		_ = {rootNamespace}.AllDiscoveredImplementations.IsInitialized;
//
// 		return services;
// 	}}
// }}
//
// public static class ProxyImplementations
// {{
// 	public static void Initialize()
// 	{{
// 		// Calls the type constructor of all types that are implemented in this assembly.
// 		_ = {rootNamespace}.AllDiscoveredImplementations.IsInitialized;
// 	}}
// }}
// ";
// 		
// 		var implementationIdFileName = FileNameHelpers.GetFileName("ProxyInitializationGenerator", configOptionsProvider);
// 		context.AddSource(implementationIdFileName, SourceText.From(code, Encoding.UTF8));
// 	}
// }
